name: Create PR

# Controls when the action will run. Triggered when another module posts a repository_dispatch event
on:
  repository_dispatch:
    types: [released]

jobs:
  update-modules:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update modules
        id: update-modules
        run: |
          OUTPUT_FILE="$PWD/module-output"

          ./.github/scripts/update-modules.sh "${OUTPUT_FILE}"

          source "${OUTPUT_FILE}"
          rm "${OUTPUT_FILE}"

          echo "::set-output name=git-slug::${GIT_SLUG}"
          echo "::set-output name=release::${RELEASE}"
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Updates ${{ steps.update-modules.outputs.git-slug }} to ${{ steps.update-modules.outputs.release }}"
          commit-message: "Updates ${{ steps.update-modules.outputs.git-slug }} to ${{ steps.update-modules.outputs.release }}"
          token: ${{ secrets.TOKEN }}
          signoff: true
          branch: patch
          delete-branch: true
          labels: chore,patch
          reviewers: ${{ secrets.ASSIGNEES }}
